name: Zola

on: [push, pull_request]

jobs:
  zola:
    runs-on: ubuntu-latest
    env:
      BASE_URL: https://github.com/getzola/zola/releases/download
      VERS: v0.10.1
      ARCH: x86_64-unknown-linux-gnu
      # https://github.com/marketplace/actions/github-pages#warning-limitation
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Lint
      uses: avto-dev/markdown-lint@v1
      with:
        args: '.'
        config: '.markdownlint.json'
    - name: Install Zola
      run: curl -L ${BASE_URL}/${VERS}/zola-${VERS}-${ARCH}.tar.gz | tar -xz
    - run: git submodule sync --recursive
    - run: git submodule update --init --recursive
    - run: ./zola --version
    - run: ./zola build
    - name: Deploy
      if: github.ref == 'refs/heads/master'
      uses: crazy-max/ghaction-github-pages@v1
      with:
        build_dir: public
        target_branch: gh-pages
        keep_history: true
